### ISSUE TITLE
[TASK] Define problem statements and algorithm descriptions

### ISSUE THREAD

**Issue by Jarrus00** [WSU-CPTS415-ParquetParkour/Amazon-CoPurchasing#17]
_Background_:
For the MS03 Statement, we need to define the problem statement(s) and algorithm(s) that the project is aiming to address.  Much of this can be derived from the MS01 statement, but may require some additional information regarding specific algorithms.

_Success Criteria_:
1. Problem statement(s) are documented along with the input, output, and goal of the algorithm developed to address them.
2. Information from 1. is compiled into the [MS03 Statement](https://github.com/WSU-CPTS415-ParquetParkour/Amazon-CoPurchasing/wiki/MS03-Statement) draft.
3. Proposals are approved by the team.

**Comment by catdennis** [comment]
collaborative filtering uses similarities between users and items simultaneously to provide recommendations. This allows for serendipitous recommendations; that is, collaborative filtering models can recommend an item to user B based on the interests of a similar user A.

Input: User A purchase history

Output: 5 recommendations for User B, based off the purchases of user A

Goal: Our goal is to implement a recommender system so we can provide recommendations for amazon users. This will hopefully encourage users to buy more products and ultimately boost revenue for amazon.
