### ISSUE TITLE
[TASK] Final report - Introduction

### ISSUE THREAD

**Issue by Jarrus00** [WSU-CPTS415-ParquetParkour/Amazon-CoPurchasing#35]
_Background_:
We need an introductory segment to familiarize readers with the impetus for this project.

_Problem_:
Why should end users care about this project?  What does this mean for them?

_Success Criteria_:
1. From the prompt on Canvas: "What is it that you are trying to solve/achieve and why does it matter."
2. Subsections are present which additionally describe our base environment configuration and the dataset.
3. References are cited and included in a subsection at the end.

**Comment by alexjking13** [comment]
Our project is designed to collect, process, and analyze data from Amazon purchasing history from the Stanford Network Analysis Project. The main goal is to create a product, that allows the user to obtain results of searches they make to the database. The user should be able to determine which category they want to search under, then narrow their search with specific values pertaining to the category. Once this is done, they can narrow the search even further by making comparisons and using logical operations. There is also a number of algorithms implemented along with this base search, such as collaborative filtering, backward expanding search, and bidirectional search. The data is stored in a Neo4j graph database. This allows us to more easily search things like products that are similar to one another as well as non-searchable attributes. 

This product could be quite helpful to someone who seeks a deeper understanding of purchasing habits on Amazon, as well as trends within these purchases. In specific, user trends are available to search using supervised learning. The user interface is developed in QT Designer, and the code is developed in VSCode. We also loaded the data into a neo4j database, and this took upwards of 16 hours on initial entry. Later on, after using a different algorithm as discusses later in this report we were able to speed up this process, and many others along the way.

**Comment by Jarrus00** [comment]
Integrated into final report.

**Comment by alexjking13** [comment]
There are a number of results from this project that are noteworthy, and can be quite interesting or useful to someone studying buying habits and patterns of Amazon users. These include searches such as popular items, typical user habits, and many more. These are discussed in depth later in the report. There are a range of uses for the information found in this project and can be useful for more researchers than just those wanting to analyze the data. Some applications for this information can be useful for psychologists and economists gaining an understanding of purchasing habits of people, and help them gain a deeper understanding of the current economic climate.
