### ISSUE TITLE
[TASK] Define searchable attributes for end-user queries

### ISSUE THREAD

**Issue by Jarrus00** [WSU-CPTS415-ParquetParkour/Amazon-CoPurchasing#9]
_Background_:
The co-purchasing dataset has a variety of attributes which are of value to end users performing research.

_Problem_:
End users will not have direct access to the attributes within the co-purchasing dataset, so we need to identify these to ensure that they are surfaced correctly in the pseudo-SQL they will be using.

_Success Criteria_:
1. The existing attributes and their data types (string, integer, float, etc.) are known.
2. The types of valid comparison operators are known for each attribute.
3. The above information is documented in the wiki for reference.

**Comment by catdennis** [comment]
Searchable attributes:
Title
Group~Category(book,dvd,video,music)
Reviews

These are user friendly searchable attributes in order of most important. 
While using an ID number might be the easiest or tastes way to find a product, the likelihood a customer knows the number is low. By searching for a more general attribute like title they can brows a selection of items that match their search.
